version: 1
labels:
  - label: "anime-additions"
    files:
      - "**/anime-wallpapers/**"

  - label: "nature-additions"
    files:
      - "**/Nature/**"

  - label: "random-additions"
    file:
      - "**/random/**"

  - label: "illustration-additions"
    files:
      - "**/illustrations/**"

  - label: "enhancement"
    files:
      - ".github/.* "

  - label: "readme_update"
    files:
      - "**/README.md"

  - label: "CONTRIBUTION_update"
    files:
      - "**/CONTRIBUTION.md"
